### PR TITLE
Add remaining pages

### PR DESCRIPTION
**Pull request by gboone**
Test the following
- [x] Error pages work and fit to the design of other pages.
- [x] (Optional) Press page looks OK
- [x] Team page ~~works and looks OK~~ redirects to homepage or `/`
- [x] Redirects work correctly for PIF pages
- [x] Redirects work correctly for tags
- [x] /dashboard redirects… somehwere
- [x] /feed/ should redirect to feed.xml

URL: https://federalist.18f.gov/preview/18F/beta.18f.gov/add-pages/

### CODE REVIEW

**Comment by gboone** [comment]
A couple notes for @maya and others reviewing:
1. Error pages need some styling
2. Team page is what it is. There are a whole bunch of people in there that aren't represented and it needs some significant styling love. Upshot: [I wrote up a quick and dirty script to carve out the body of the existing team profiles](https://gist.github.com/gboone/cd1b01c8501759418a5fd64f9b33072d)
3. /dashboard/ redirects to 18f.gsa.gov for now. Might not be a great UX.
4. The press page: I literally just scraped the contents of the existing press page and spit them into the html file. It actually doesn't look too bad but you still might want to take a look at it. Like we said earlier, it's not the press page we want but until we have better content for a press kit, let's not spend too much time designing this one.

**Comment by maya** [comment]
1.) Styled 404 and 500 pages in 39ee629. https://federalist.18f.gov/preview/18F/beta.18f.gov/add-pages/404/ https://federalist.18f.gov/preview/18F/beta.18f.gov/add-pages/500/

screen shot 2016-07-21 at 4 47 36 pm

screen shot 2016-07-21 at 4 47 30 pm

2.) Not seeing any people output on the team page for some reason: https://federalist.18f.gov/preview/18F/beta.18f.gov/add-pages/team/

4.) Press page: I think it's OK, but it's missing some images. Also, do we need all those "back to top" links after every paragraph? https://federalist.18f.gov/preview/18F/beta.18f.gov/add-pages/press/

**Comment by maya** [comment]
Did we also need these pages?

Standard error pages (keep but might need some designing)
- [x] 404.html
- [x] 500.html

Directories
- [x] april-fools — archive of April Fools Day things we did at 18F, keep for posterity. Only catch is the 2016 one relies on some team profiles. Think about how we might replace them. — Low priority
- [x] dashboard – 18f.gsa.gov/dashboard/ (Sunset, not moving with the site), will probably want to redirect /dashboard/ requests somewhere.
- [x] pif — We probably want to keep something that redirects 18f.gsa.gov/pif to pif.gov (Though a fix is in, the irony of this not currently working is not lost on me.)
- [x] press - Need to keep all of this, though the content needs some work. — Low priority

Archives
- [x] feed.md - Probably want to keep this, redirects requests for /feed/ to /feed.xml Alternatively, figure out a way to make the jekyll-feed plugin accept both addresses.
- [x] team.html — This is /team/ ~~we want to do something about this but unclear what or how just yet.~~ we will redirect to /blog/ or /, cc @gboone. 

Pages
- [x] developer.md – Keep
- [x] developers.md – Keep
- [x] humans.txt – Keep and update (currently relies on the team.json file downloaded infrequently from the team api)
- [x] robots.txt – Keep
- [x] thank-you.md – Keep (or change the newsletter’s post-submission action)

**Comment by gboone** [comment]
The team members should show up. Apparently I forgot to add all the `_team` documents to the commit. I'll figure out the rest today.

**Comment by gboone** [comment]
All of these Travis checks are fails negatives. We do not need Travis' 👌 to merge this.

**Comment by maya** [comment]
LGTM!

**Pull request merged**
