### PR TITLE
Add "View on GitHub" link to footer

### PR DESCRIPTION
**Pull request by maya**
Currently we don't have a link to GitHub on the site and this adds it.

This is what it looks like: 

screen shot 2016-08-20 at 11 32 36 am

cc: @gboone @elainekamlley

### CODE REVIEW

**Comment by gboone** [comment]
Do we have an "edit this page" link somewhere? Maybe we put that here?

**Comment by maya** [comment]
@gboone we don't have that.

**Comment by maya** [comment]
Also, cc @awfrancisco since this is a small content change as well.

**Comment by awfrancisco** [comment]
Looks good to me

**Pull request merged**
